export const categories = [
  {
    id: 1,
    title: "مشوى على الفحم",
    image: "../assets/food-cat-1.png",
  },
  {
    id: 2,
    title: "فرن فلاحى",
    image: "../assets/food-cat-2.png",
  },
  {
    id: 3,
    title: "مطبخ حجوجه",
    image: "../assets/food-cat-3.png",
  },
  {
    id: 4,
    title: "الجريل",
    image: "../assets/food-cat-4.png",
  },
  {
    id: 5,
    title: "حمام وبط",
    image: "../assets/food-cat-5.png",
  },
  {
    id: 6,
    title: "محشى بيتى",
    image: "../assets/food-cat-6.png",
  },
  {
    id: 7,
    title: "سفرة",
    image: "../assets/food-cat-7.png",
  },
  {
    id: 8,
    title: "محمر بالزبدة",
    image: "../assets/food-cat-8.png",
  },
  {
    id: 9,
    title: "طواجن فلاحى",
    image: "../assets/food-cat-9.png",
  },
  {
    id: 10,
    title: "وجبة أطفال",
    image: "../assets/food-cat-10.png",
  },
  {
    id: 11,
    title: "مشروبات",
    image: "../assets/food-cat-11.png",
  },
  {
    id: 12,
    title: "حلو الحاجة",
    image: "../assets/food-cat-12.png",
  },
  {
    id: 13,
    title: "فتة ورز",
    image: "../assets/food-cat-13.png",
  },
  {
    id: 14,
    title: "شوربة",
    image: "../assets/food-cat-14.png",
  },
  {
    id: 15,
    title: "السلاطات",
    image: "../assets/food-cat-15.png",
  },
];

export const products = [
  // cat 1
  {
    id: 1,
    categoryId: 1,
    title: "ربع كفته ضانى سبشيال",
    price: 175.44,
    image: "./assets/food-1.png",
  },
  {
    id: 2,
    categoryId: 1,
    title: "ربع سجق",
    price: 153.51,
    image: "./assets/food-1.png",
  },
  {
    id: 3,
    categoryId: 1,
    title: "ربع كباب وكفته ضانى",
    price: 214.91,
    image: "./assets/food-1.png",
  },
  {
    id: 4,
    categoryId: 1,
    title: "ربع كباب وكفته بتلو",
    price: 263.16,
    image: "./assets/food-1.png",
  },
  {
    id: 5,
    categoryId: 1,
    title: "ربع كباب ضانى",
    price: 263.16,
    image: "./assets/food-1.png",
  },
  {
    id: 6,
    categoryId: 1,
    title: "ثلث ريش وكفتة",
    price: 298.25,
    image: "./assets/food-1.png",
  },
  {
    id: 7,
    categoryId: 1,
    title: "ثلث كباب وريش",
    price: 298.25,
    image: "./assets/food-1.png",
  },
  {
    id: 8,
    categoryId: 1,
    title: "ربع ريش صافى",
    price: 342.11,
    image: "./assets/food-1.png",
  },
  {
    id: 9,
    categoryId: 1,
    title: "ربع ريش صافى",
    price: 342.11,
    image: "./assets/food-1.png",
  },
  {
    id: 10,
    categoryId: 1,
    title: "صينية حبايب الحاجة",
    price: 2719.3,
    image: "./assets/food-1.png",
  },
  {
    id: 11,
    categoryId: 1,
    title: "صينية حجوجه",
    price: 1491.23,
    image: "./assets/food-1.png",
  },
  {
    id: 12,
    categoryId: 1,
    title: "نيفه الحاجة",
    price: 350.88,
    image: "./assets/food-1.png",
  },
  {
    id: 13,
    categoryId: 1,
    title: "ترويقه (ضلع)",
    price: 324.56,
    image: "./assets/food-1.png",
  },
  {
    id: 14,
    categoryId: 1,
    title: "ربع شيش طاووك",
    price: 118.42,
    image: "./assets/food-1.png",
  },
  {
    id: 15,
    categoryId: 1,
    title: "نص فرخه مشويه",
    price: 127.19,
    image: "./assets/food-1.png",
  },
  {
    id: 16,
    categoryId: 1,
    title: "ربع كبده ضانى مشويه",
    price: 192.98,
    image: "./assets/food-1.png",
  },

  // cat 2
  {
    id: 17,
    categoryId: 2,
    title: "صينية رقاق",
    price: 118.42,
    image: "./assets/food-2.png",
  },
  {
    id: 18,
    categoryId: 2,
    title: "صينية رقاق حجوجه محشى بط مخلى",
    price: 175.44,
    image: "./assets/food-2.png",
  },
  {
    id: 19,
    categoryId: 2,
    title: "رقاق قشطة زبدة",
    price: 135.96,
    image: "./assets/food-2.png",
  },
  {
    id: 20,
    categoryId: 2,
    title: "ارز معمر لبن وقشطة بلدى",
    price: 105.26,
    image: "./assets/food-2.png",
  },

  // cat 3
  {
    id: 21,
    categoryId: 3,
    title: "ورق عنب كوارع",
    price: 241.23,
    image: "./assets/food-3.png",
  },
  {
    id: 22,
    categoryId: 3,
    title: "ورق عنب باللحمة",
    price: 368.42,
    image: "./assets/food-3.png",
  },
  {
    id: 23,
    categoryId: 3,
    title: "موزة ضانى بالبطاطس",
    price: 385.96,
    image: "./assets/food-3.png",
  },
  {
    id: 24,
    categoryId: 3,
    title: "ورق عنب بالموزة الضانى",
    price: 368.42,
    image: "./assets/food-3.png",
  },
  {
    id: 25,
    categoryId: 3,
    title: "لوحه ضانى ورق عنب",
    price: 359.65,
    image: "./assets/food-3.png",
  },
  {
    id: 26,
    categoryId: 3,
    title: "لوحه ضانى بالبطاطس",
    price: 293.86,
    image: "./assets/food-3.png",
  },
  {
    id: 27,
    categoryId: 3,
    title: "رقبة ضانى ورق عنب",
    price: 359.65,
    image: "./assets/food-3.png",
  },
  {
    id: 28,
    categoryId: 3,
    title: "رقبة ضانى بالبطاطس",
    price: 350.88,
    image: "./assets/food-3.png",
  },
  {
    id: 29,
    categoryId: 3,
    title: "لحمة بالبطاطس",
    price: 175.44,
    image: "./assets/food-3.png",
  },

  // cat 4
  {
    id: 30,
    categoryId: 4,
    title: "ربع كبده ضانى مشويه",
    price: 192,
    image: "./assets/food-4.png",
  },
  {
    id: 31,
    categoryId: 4,
    title: "ربع كبده ضانى مشويه",
    price: 192,
    image: "./assets/food-4.png",
  },

  // cat 5
  {
    id: 32,
    categoryId: 5,
    title: "حمام محشى",
    price: 127.19,
    image: "./assets/food-5.png",
  },
  {
    id: 33,
    categoryId: 5,
    title: "برام برج الحمام",
    price: 162.28,
    image: "./assets/food-5.png",
  },
  {
    id: 34,
    categoryId: 5,
    title: "حمام قشطة",
    price: 149.12,
    image: "./assets/food-5.png",
  },
  {
    id: 35,
    categoryId: 5,
    title: "مزاليكا",
    price: 109.65,
    image: "./assets/food-5.png",
  },
  {
    id: 36,
    categoryId: 5,
    title: "نص بطة",
    price: 307.02,
    image: "./assets/food-5.png",
  },
  {
    id: 37,
    categoryId: 5,
    title: "نص بطة ورق عنب",
    price: 342.11,
    image: "./assets/food-5.png",
  },
  {
    id: 38,
    categoryId: 5,
    title: "نص بطة مع رز وملوخية",
    price: 333.33,
    image: "./assets/food-5.png",
  },

  // cat 6
  {
    id: 39,
    categoryId: 6,
    title: "ورق عنب",
    price: 61.4,
    image: "./assets/food-6.png",
  },
  {
    id: 40,
    categoryId: 6,
    title: "محشى كرنب",
    price: 52.63,
    image: "./assets/food-6.png",
  },
  {
    id: 41,
    categoryId: 6,
    title: "بتنجان وفلفل (خضار)",
    price: 43.86,
    image: "./assets/food-6.png",
  },
  {
    id: 42,
    categoryId: 6,
    title: "ممبار",
    price: 61.4,
    image: "./assets/food-6.png",
  },
  {
    id: 43,
    categoryId: 6,
    title: "سرفيس محاشى",
    price: 175.44,
    image: "./assets/food-6.png",
  },

  // cat 7
  {
    id: 44,
    categoryId: 7,
    title: "ملوخية",
    price: 52.63,
    image: "./assets/food-7.png",
  },

  // cat 8
  {
    id: 45,
    categoryId: 8,
    title: "كبده بتلو",
    price: 210.53,
    image: "./assets/food-8.png",
  },
  {
    id: 46,
    categoryId: 8,
    title: "سجق زبدة",
    price: 171.05,
    image: "./assets/food-8.png",
  },
  {
    id: 47,
    categoryId: 8,
    title: "كبدة سبشيال ضانى فى الليه",
    price: 171.05,
    image: "./assets/food-8.png",
  },
  {
    id: 48,
    categoryId: 8,
    title: "مناب العمدة جديد",
    price: 307.02,
    image: "./assets/food-8.png",
  },
  {
    id: 49,
    categoryId: 8,
    title: "مخاصى زبدة",
    price: 171.05,
    image: "./assets/food-8.png",
  },

  // cat 9
  {
    id: 50,
    categoryId: 9,
    title: "طاجن بصلية",
    price: 184.21,
    image: "./assets/food-9.png",
  },
  {
    id: 51,
    categoryId: 9,
    title: "طاجن عكاوى",
    price: 350.88,
    image: "./assets/food-9.png",
  },
  {
    id: 52,
    categoryId: 9,
    title: "طاجن ترويقه بالبصل",
    price: 333.33,
    image: "./assets/food-9.png",
  },
  {
    id: 53,
    categoryId: 9,
    title: "طاجن فريك باللحمة",
    price: 184.21,
    image: "./assets/food-9.png",
  },
  {
    id: 54,
    categoryId: 9,
    title: "طاجن باميه باللحمة",
    price: 184.21,
    image: "./assets/food-9.png",
  },

  // cat 10
  {
    id: 55,
    categoryId: 10,
    title: "ملوخية ورز وكوكو",
    price: 157.89,
    image: "./assets/food-10.png",
  },

  // cat 11
  {
    id: 56,
    categoryId: 11,
    title: "شاى",
    price: 21.93,
    image: "./assets/food-11.png",
  },
  {
    id: 57,
    categoryId: 11,
    title: "حاجة ساقعة",
    price: 21.93,
    image: "./assets/food-11.png",
  },
  {
    id: 58,
    categoryId: 11,
    title: "تمر هندى طبيعى",
    price: 26.32,
    image: "./assets/food-11.png",
  },
  {
    id: 59,
    categoryId: 11,
    title: "سوبيا حليب وقشطة",
    price: 39.47,
    image: "./assets/food-11.png",
  },
  {
    id: 60,
    categoryId: 11,
    title: "مياه معدنية",
    price: 13.16,
    image: "./assets/food-11.png",
  },

  // cat 12
  {
    id: 61,
    categoryId: 12,
    title: "مهلبية فرن بالحليب والقشطة",
    price: 26.32,
    image: "./assets/food-12.png",
  },
  {
    id: 62,
    categoryId: 12,
    title: "بسبوسة بالسمن البلدى",
    price: 39.47,
    image: "./assets/food-12.png",
  },
  {
    id: 63,
    categoryId: 12,
    title: "بسبوسة قشطة حجوجة",
    price: 70.18,
    image: "./assets/food-12.png",
  },

  // cat 13
  {
    id: 64,
    categoryId: 13,
    title: "فتة محبشة",
    price: 61.4,
    image: "./assets/food-13.png",
  },
  {
    id: 65,
    categoryId: 13,
    title: "فتة كوارع",
    price: 236.84,
    image: "./assets/food-13.png",
  },
  {
    id: 66,
    categoryId: 13,
    title: "فتة موزة مخلية كندوز",
    price: 263.16,
    image: "./assets/food-13.png",
  },
  {
    id: 67,
    categoryId: 13,
    title: "فتة لوحة ضانى",
    price: 368.42,
    image: "./assets/food-13.png",
  },
  {
    id: 68,
    categoryId: 13,
    title: "فتة لحمة",
    price: 192.98,
    image: "./assets/food-13.png",
  },
  {
    id: 69,
    categoryId: 13,
    title: "فتة رقبة ضانى",
    price: 359.65,
    image: "./assets/food-13.png",
  },
  {
    id: 70,
    categoryId: 13,
    title: "رز أبيض",
    price: 43.86,
    image: "./assets/food-13.png",
  },
  {
    id: 71,
    categoryId: 13,
    title: "رز شعرية",
    price: 43.86,
    image: "./assets/food-13.png",
  },
  {
    id: 72,
    categoryId: 13,
    title: "فتة موزة ضانى",
    price: 385.96,
    image: "./assets/food-13.png",
  },

  // cat 14
  {
    id: 73,
    categoryId: 14,
    title: "شوربة لسان",
    price: 26.32,
    image: "./assets/food-14.png",
  },
  {
    id: 73,
    categoryId: 14,
    title: "شوربة حمام",
    price: 17.54,
    image: "./assets/food-14.png",
  },
  {
    id: 73,
    categoryId: 14,
    title: "شوربة كوارع سادة",
    price: 17.54,
    image: "./assets/food-14.png",
  },

  // cat 15
  {
    id: 73,
    categoryId: 15,
    title: "بلدى",
    price: 8.77,
    image: "./assets/food-15.png",
  },
  {
    id: 74,
    categoryId: 15,
    title: "طحينة",
    price: 13.16,
    image: "./assets/food-15.png",
  },
  {
    id: 75,
    categoryId: 15,
    title: "طرشى",
    price: 8.77,
    image: "./assets/food-15.png",
  },
  {
    id: 76,
    categoryId: 15,
    title: "باب غنوج",
    price: 13.16,
    image: "./assets/food-15.png",
  },
  {
    id: 77,
    categoryId: 15,
    title: "جرجير",
    price: 8.77,
    image: "./assets/food-15.png",
  },
  {
    id: 78,
    categoryId: 15,
    title: "بتنجان مخلل",
    price: 13.16,
    image: "./assets/food-15.png",
  },
  {
    id: 79,
    categoryId: 15,
    title: "طماطم متبلة",
    price: 13.16,
    image: "./assets/food-15.png",
  },
  {
    id: 80,
    categoryId: 15,
    title: "جينة قديمة فلاحى",
    price: 26.32,
    image: "./assets/food-15.png",
  },
  {
    id: 81,
    categoryId: 15,
    title: "طرنشات حجوجة بالدقة",
    price: 30.7,
    image: "./assets/food-15.png",
  },
  {
    id: 82,
    categoryId: 15,
    title: "مورتة فلاحى",
    price: 26.32,
    image: "./assets/food-15.png",
  },
];
